### ISSUE TITLE
Initial proposal

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-kubernetes#1]
We should create the community maintained Galaxy deployment on Kubernetes based on:
- [x] A Helm Chart for Galaxy. 
- [ ] A minimal Galaxy docker image
  - [ ] Which relies on ansible-galaxy-extras for installation of Galaxy
  - [ ] That can accept injection of settings on the galaxy.ini file at runtime through environment  variables (the image needs to have a way of enacting this into the ini file).
  - [ ] From ubuntu:~~16.04?~~ Apparently has issues with nginx Galaxy plugin according to @bgruening, might need to be 14.04.
- [x] Uses Postgresql in a separate Pod.
  - [x] Users authentication and database connection details are injected at runtime through Kubernetes Secret/Config Maps.
  - [x] Galaxy Communicates to Postgresql through Service.
  - [x] Uses a standard Postgresql docker image (9.3 tested at PhenoMeNal)
- [ ] Uses nginx on the same pod as galaxy, separate container
  - [ ] Uses standard nginx container
  - [ ] Config injected at runtime through config maps.
- [ ] Guide on how to make your own flavour of the Galaxy container, based on the minimal one, and following the paradigm that bgruening/docker-galaxy-stable has.
  - [ ] Can change settings on runtime as well.
  - [ ] Tools XML wrappers are part of the flavours.
- [x] Galaxy ReplicationController accesible through Service.

Helm is a package manager for Kubernetes which allows parametrised deployments, with sensible defaults. That means that other people can use the same Helm setup, but changing through parameters whatever we decide it can be changed, like the docker container used for Galaxy.

That for now. Will add more soon.

**Comment by pcm32** [comment]
I have been working on helm-based deployments for Kubernetes for some days now. I have made some progress in setting a galaxy simple deployment (just galaxy, for tool development/testing purposes) and an initial galaxy with postgresql, which should grow into a galaxy production deployment. The beauty of helm is that deployments can be left with parameters, so you can do things like:

```
helm install galaxy-helm-repo/galaxy-simple --set image.name=<my_preferred_docker_image>,my.other.variable=<other_var_value,db.database.pass=<my-password>
```

You can see the Helm charts here:
https://github.com/pcm32/galaxy-helm-charts/tree/develop

Currently the helm charts are using my phenomenal docker image of galaxy as we (participants of the original email thread) don’t have yet a slim one to use as we discussed, but I hope that someone can start that at some point, so that I can add the Kubernetes necessary bits there.

If you have a Kubernetes cluster, you need to install helm on your client machine:
https://github.com/kubernetes/helm#install

and then set up the cluster by running `helm init` on the machine that has kubectl configure to talk to your cluster. After that you can run:

```
# only needed once per client:
helm repo add galaxy-helm-repo https://pcm32.github.io/galaxy-helm-charts/ 

# for each new deployment (normally you don’t include the Persistent Volume definition on the Helm chart 
# as it is site specific: some will use NFS, some GlusterFS, some s3, etc).
kubectl create -f your_favourite_persistent_volume.yaml
# then either:
helm install galaxy-helm-repo/galaxy-simple
# or instead
helm install galaxy-helm-repo/galaxy-postgres-chart
```

That will lift galaxy with a ReplicationController and expose it on all IPs of the cluster on port 30700. 

We could share this approach and everyone uses whatever base docker image they want (these docker images just need to provide some minimal capabilities) for their deployment.

Let me know if you are happy with this to push as well to this repo that Enis started (currently just pushing to a different remote as some of you had some reservations).

**Comment by pcm32** [comment]
@afgane can you add Alex and Nuwan to this discussion? I don't know their git users. Thanks!

**Comment by afgane** [comment]
Can't seem to add @zfrenchee but I guess Alex you can subscribe yourself?

**Comment by zfrenchee** [comment]
I think it's because I'm not a member of `galaxyproject`

**Comment by pcm32** [comment]
This is quite outdated, and most objectives achieved, so I will close this now. Please reopen if needed.
