### ISSUE TITLE
Galaxy-stable chart doesn't start up with default settings.

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy-kubernetes#10]
How to recreate:
I checked out the develop branch and tested against minikube. Did not make any changes - simply ran a `helm install .`

The galaxy-stable chart installs without a hitch. However, when attempting to access the galaxy service via the NodePort, it simply returned a 404. The galaxy container's logs revealed the error:
`
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
`
It appears that the GALAXY_CONFIG_DATABASE_CONNECTION is not being overridden as expected.

I then exec'd into the container and manually ran the following:
```
export GALAXY_CONFIG_DATABASE_CONNECTION=postgresql://galaxy:change-me@postgresql-for-galaxy/galaxydb?client_encoding=utf8
/usr/bin/startup
```
Still the same error.

Finally, I edited galaxy-central/config/galaxy.ini, and set the database connection manually there. It then proceeded to startup and connected to the postgres database, instead of sqlite. However, it ran all the migrations from scratch, indicating that it's not a database with migrations included.

Finally, it failed with the following:
```
Traceback (most recent call last):
  File "/export/galaxy-central/lib/galaxy/webapps/galaxy/buildapp.py", line 58, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
  File "/export/galaxy-central/lib/galaxy/app.py", line 185, in __init__
    self.job_manager = manager.JobManager( self )
  File "/export/galaxy-central/lib/galaxy/jobs/manager.py", line 23, in __init__
    self.job_handler = handler.JobHandler( app )
  File "/export/galaxy-central/lib/galaxy/jobs/handler.py", line 33, in __init__
    self.dispatcher = DefaultJobDispatcher( app )
  File "/export/galaxy-central/lib/galaxy/jobs/handler.py", line 764, in __init__
    self.job_runners = self.app.job_config.get_job_runner_plugins( self.app.config.server_name )
  File "/export/galaxy-central/lib/galaxy/jobs/__init__.py", line 632, in get_job_runner_plugins
    rval[id] = runner_class( self.app, runner[ 'workers' ], **runner.get( 'kwds', {} ) )
  File "/export/galaxy-central/lib/galaxy/jobs/runners/kubernetes.py", line 44, in __init__
    assert KubeConfig is not None, K8S_IMPORT_MESSAGE
AssertionError: The Python pykube package is required to use this feature, please install it or correct the following error:
ImportError No module named pykube.config
root@torpid-kudu-galaxy-stable-bbcf5b445-4
```

Is this a problem with an out-of-date container (I have not tested this chart on? @pcm32 Where can I view the DockerFile that was used to build pcm32/galaxy-stable-k8s? I checked here: https://hub.docker.com/r/pcm32/galaxy-stable-k8s/ but it does not display the Dockerfile.

The docker images used by minikube were listed as:
```
pcm32/galaxy-stable-k8s                                          latest              a4e5ec729667        6 months ago        898MB
pcm32/galaxy-stable-k8s-init                                     latest              01867b81731e        7 months ago        1.41GB
```

**Comment by nuwang** [comment]
I forgot to add. The repo I used was:
`
helm repo add https://pcm32.github.io/galaxy-helm-charts
`

**Comment by pcm32** [comment]
Thanks for pointing this out! Because of the minikube / actual cluster duality, I guess there is no clear default, but we could try to make it as smooth as possible. I don't think that in the documentation I mentioned any default case though, but using some example configs (which I will look into making more clear and standard). Currently blocked becuase of some issues with 18.01 images, but I will work on that this week.

**Comment by pcm32** [comment]
This [addition to docs](https://github.com/galaxyproject/galaxy-kubernetes/blob/feature/add-container-building-script/README-galaxy-stable.md#tldr) should help as a default minikube, although the vanilla instance lifted is more or less useless as it doesn't include much tools and it won't submit jobs to k8s because stock images are not configured to do so.

**Comment by pcm32** [comment]
Given #11 I will close this, but please reopen if needed.
