### ISSUE TITLE
Install not prefixed with release name

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy-kubernetes#15]
Currently, the galaxy installation is not prefixed with the release name, which means that only one instance of the chart can be installed per namespace. It would be good to support the standard convention of prefixing by release name so that we can support multiple galaxy installations. This will be particularly useful in future when we have multiple users having private galaxys, as well as during testing so that previous artefacts don't affect the current installation. Low priority item for now.

**Comment by pcm32** [comment]
Hi! This is the case on the galaxy-stable chart, which is the one used for the community images.

**Comment by pcm32** [comment]
I will close this given my comment above, but please reopen if needed.
