### ISSUE TITLE
[2.0] db-connection config map doesn't get deleted on helm delete

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-kubernetes#24]
Using the new chart specification:

```
 helm list
NAME             	REVISION	UPDATED                 	STATUS	CHART              	NAMESPACE
existing-platypus	1       	Tue Jul 10 09:44:57 2018	FAILED	galaxy-stable-2.0.0	default  
C02WF18BHV2H:galaxy-kubernetes pmoreno$ helm delete existing-platypus
release "existing-platypus" deleted
C02WF18BHV2H:galaxy-kubernetes pmoreno$ helm install -f ../container-galaxy-sc-tertiary/helm-configs/tertiary-portals-galaxy-18.05-minikube.yaml ./galaxy-stable
Error: configmaps "db-connection" already exists
```

Might be an issue of the chart not starting correctly the first time though... will monitor.

**Comment by pcm32** [comment]
Yes, I can confirm it persists even after a correct deployment and deletion (db-connection).

**Comment by nuwang** [comment]
This seems to be coming from the postgres-for-galaxy chart, which is no longer used in 2.0?

**Comment by pcm32** [comment]
Could be the reason, I noticed I had the tar.gz for the other chart, which is ignored by github....

**Comment by pcm32** [comment]
But then I have been running for a while now without the old postgres tar.gz, and still see these. I'll come back to this when I sort out my http issues on 18.05....
