### ISSUE TITLE
TODOs for integration with docker-galaxy-stable compose containers

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-kubernetes#3]
These are the main actionables I need to go through to have a first container based on galaxy-stable compose containers working with the helm deployment, as discussed in #2 . More to come here, as I go through them and find dependent tasks.

- [x] Fix pykube version on ansible-galaxy-extras to 0.15.0
- [ ] Create proposal(1) on docker-galaxy-stable for intermediate image between galaxy-base and galaxy-web, from where galaxy-k8s could stem from.
- [x] Create base galaxy-k8s image (2) based on proposal (1).
- [ ] Make `ansible/run_galaxy_config.sh` work on /galaxy-central/ on image (2). Alternatively, replace its functionality.
  - [x] Inject workflows given.
  - [x] Setup database.
  - [x] Setup admin user.
- [ ] Handle galaxy.ini.injected from user on image (2)
- [x] Add missing k8s_* vars on job_conf jinja template on ansible-galaxy-central.
- [ ] Write down what seem to be our minimal dependencies (or link to such revision).
- [x] Try using GALAXY_RELEASE related vars as in https://github.com/bgruening/docker-galaxy-stable/blob/master/galaxy/Dockerfile#L14 to set repo and branch to use for build.
- [ ] Evaluate whether this strategy serves the purpose of sharing tools with jobs pods: https://github.com/bgruening/docker-galaxy-stable#integrating-non-tool-shed-tools-into-the-container--toc
- [ ] Use this approach for the image (2) personalization: https://github.com/bgruening/docker-galaxy-stable#personalize-your-galaxy--toc
- [x] Handle missing datatypes.
- [x] Helm needs to use both a galaxy-init and a galaxy-web derived images for a minimal working example.
- [x] Sort out issue with larger parts of job_conf.xml that we need injected and that are not easily injectable through variables.
   - [x] Deal with handlers in job_conf and galaxy.ini
      - [x] Add to the job_conf the handlers and leave them commented in the phenomenal current setup.
      - [x] Figure out handlers setup in compose images. 
   - [x] Dynamic destinations.
   - [x] Container destinations.
- [ ] Harmonize eventually directory structure.

**Comment by bgruening** [comment]
Regarding missing datatypes - do you have a list? We should get them into Galaxy 18.01 directly.

**Comment by pcm32** [comment]
Datatypes are mostly from W4M XCMS:
```
# Missing XCMS datatypes for w4m
COPY external-datatypes/rdata_xcms_datatype.py /galaxy/lib/galaxy/datatypes/
COPY external-datatypes/rdata_camera_datatype.py /galaxy/lib/galaxy/datatypes/
COPY external-datatypes/no_unzip_datatypes.py /galaxy/lib/galaxy/datatypes/
COPY external-datatypes/nmrml_datatype.py /galaxy/lib/galaxy/datatypes/
COPY config/datatypes_conf.xml config/datatypes_conf.xml
```
from this revision: https://github.com/phnmnl/container-galaxy-k8s-runtime/tree/c6b4bea41481894eeac0e54f786b4f9b839c16e5/external-datatypes

**Comment by pcm32** [comment]
Will close this as it is mostly addressed by work on the branch feature/sync_with_galaxy_stable, which is functional albeit lacking a bit of documentation. PhenoMeNal public instances have been running on the compose setup for some months now.
