### ISSUE TITLE
Broken helm repo

### ISSUE THREAD

**Issue by eslerm** [galaxyproject/galaxy-kubernetes#35]
The [galaxy-helm-repo](https://pcm32.github.io/galaxy-helm-charts) from the README appears to be broken.

**Comment by pcm32** [comment]
Hi, thanks for reaching out. Could you paste the error that you get please?

**Comment by eslerm** [comment]
Hi pcm32. I must have made a mistake. Earlier I was getting a ImagePullBackOff error, but the helm install scripts are working for me now.
